apiVersion: rbac.authorization.k8s.io/v1beta1
# TODO: Does this need to be changed to a clusterrole?
# see  manifests in kubeflow/pipelines
kind: ClusterRole
metadata:
  name: ml-pipeline
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - kubeflow.org
  resources:
  - scheduledworkflows
  verbs:
  - create
  - get
  - list
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete

