apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

resources:
- cluster-role.yaml
- cluster-role-binding.yaml

images:
- name: gcr.io/ml-pipeline/frontend
  newName: gcr.io/arrikto/ml-pipeline-frontend
  newTag: 1.0.0-rc.2-13-gee9080f

patchesStrategicMerge:
- patches/deployment.yaml
