# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- crd.yaml
- manager.yaml
- rbac/role.yaml
- rbac/role_binding.yaml
- rbac/leader_election_role.yaml
- rbac/leader_election_role_binding.yaml
# Comment the following 3 lines if you want to disable
# the auth proxy (https://github.com/brancz/kube-rbac-proxy)
# which protects your /metrics endpoint.
- rbac/auth_proxy_service.yaml
- rbac/auth_proxy_role.yaml
- rbac/auth_proxy_role_binding.yaml

images:
- name: controller
  newName: gcr.io/arrikto-public/kubeflow/pvcviewer-controller
  newTag: v1.0-56-g5ae311f8
- name: coderaiser/cloudcmd
  newName: gcr.io/arrikto-public/kubeflow/volumes-viewer
  newTag: v14.3.0-12-g79d7536b
namespace: kubeflow

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: pvcviewer-controller-

# Labels to add to all resources and selectors.
commonLabels:
  app: pvcviewer-controller

patchesStrategicMerge:
  # Protect the /metrics endpoint by putting it behind auth.
  # Only one of manager_auth_proxy_patch.yaml and
  # manager_prometheus_metrics_patch.yaml should be enabled.
- manager_auth_proxy_patch.yaml
  # If you want your controller-manager to expose the /metrics
  # endpoint w/o any authn/z, uncomment the following line and
  # comment manager_auth_proxy_patch.yaml.
  # Only one of manager_auth_proxy_patch.yaml and
  # manager_prometheus_metrics_patch.yaml should be enabled.
#- manager_prometheus_metrics_patch.yaml

configurations:
- pvcviewer_image_configuration.yaml
