apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

images:
- name: gcr.io/kubeflow-images-public/admission-webhook
  newName: gcr.io/arrikto/admission-webhook
  newTag: v1.0.0-arr-121-g1a2f4e2
