apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline-ui
spec:
  template:
    spec:
      containers:
      - name: ml-pipeline-ui
        env:
        - name: ARGO_ARCHIVE_LOGS
          value: "true"
        - name: ARGO_ARCHIVE_PREFIX
          value: artifacts
        - name: DEPLOYMENT
          value: KUBEFLOW
        - name: DISABLE_GKE_METADATA
          value: "true"