namespace: kubeflow

commonLabels:
  app: volumes-web-app

resources:
- rbac.yaml
- service.yaml
- deployment.yaml
- virtualservice.yaml

images:
- name: gcr.io/arrikto-playground/volumes-web-app
  newName: gcr.io/arrikto-public/kubeflow/volumes-web-app
  newTag: v1.0.0-arr-47-g54cbfb01
