apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

images:
- name: gcr.io/arrikto/kubeflow/oidc-authservice
  newName: gcr.io/arrikto-public/kubeflow/oidc-authservice
  newTag: d5c2981

patchesStrategicMerge:
- patches/statefulset.yaml
