apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

images:
- name: gcr.io/arrikto/kubeflow/oidc-authservice
  newName: gcr.io/arrikto/oidc-authservice
  newTag: d10906e

patchesStrategicMerge:
- patches/statefulset.yaml
- patches/service.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: authservice
  path: patches/env.yaml

secretGenerator:
- name: oidc-authservice-client
  type: Opaque
  env: secret_params.env

configMapGenerator:
- name: oidc-authservice-parameters
  env: params.env
  # FIXME: If base's vars can somehow not be inherrited, use replace
  # instead of merge to avoid an ugly configmap with duplicate params.
  behavior: merge

generatorOptions:
  disableNameSuffixHash: true

vars:
- name: NAMESPACE
  fieldref:
    fieldPath: metadata.namespace
  objref:
    apiVersion: v1
    kind: Service
    name: authservice

resources:
- virtualservice.yaml

configurations:
- params.yaml
