apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

images:
- name: gcr.io/arrikto/kubeflow/oidc-authservice
  newName: gcr.io/arrikto-public/kubeflow/oidc-authservice
  newTag: d5c2981

patchesStrategicMerge:
- patches/statefulset.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: authservice
  path: patches/env.yaml

secretGenerator:
- name: oidc-authservice-client
  type: Opaque
  env: secret_params.env

configMapGenerator:
- name: oidc-authservice-parameters
  env: params.env
  behavior: merge

generatorOptions:
  disableNameSuffixHash: true
