[
    {"op": "replace",
     "path": "/spec/ports",
     "value": [{"name": "http2",
                "port": 8080,
                "protocol": "TCP",
                "targetPort": 80},
               {"name": "https",
                "port": 443,
                "protocol": "TCP",
                "targetPort": 443}]},
    {"op": "replace",
     "path": "/spec/type",
     "value": "ClusterIP"}
]
