apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
images:
- name: gcr.io/arrikto-public/kubeflow/reception
  newName: gcr.io/arrikto-public/kubeflow/reception
  newTag: v1.0-65-gb1cc779e