apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

resources:
- crd.yaml

patchesStrategicMerge:
- patches/crd.yaml
- patches/config-map.yaml
- patches/cluster-role.yaml

images:
- name: argoproj/argoui
  newName: argoproj/argoui
  newTag: v2.4.3
- name: argoproj/workflow-controller
  newName: argoproj/workflow-controller
  newTag: v2.8.0

configMapGenerator:
- name: workflow-controller-parameters
  env: params.env
  behavior: merge
generatorOptions:
  disableNameSuffixHash: true
vars:
- name: artifactRepositoryArchiveLogs
  objref:
    kind: ConfigMap
    name: workflow-controller-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.artifactRepositoryArchiveLogs
configurations:
- params.yaml