apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

images:
- name: gcr.io/kubeflow-images-public/notebook-controller
  newName: gcr.io/arrikto-public/kubeflow/notebook-controller
  newTag: v1.0-56-g5ae311f8
