apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base

images:
- name: gcr.io/ml-pipeline/scheduledworkflow
  newName: gcr.io/ml-pipeline/scheduledworkflow
  newTag: 1.0.0-rc.2
