apiVersion: apps/v1
kind: Deployment
metadata:
  name: persistenceagent
spec:
  template:
    spec:
      containers:
      - name: ml-pipeline-persistenceagent
        command:
        - "persistence_agent"
        - "--logtostderr=true"
        - "--ttlSecondsAfterWorkflowFinish=120"