apiVersion: apps/v1
kind: Deployment
metadata:
  name: persistenceagent
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: ml-pipeline-persistenceagent
        command:
        - "persistence_agent"
        - "--logtostderr=true"
        - "--ttlSecondsAfterWorkflowFinish=120"